### ISSUE TITLE
Multiple accounts support and app password-protected

### ISSUE THREAD

**Issue by meichengg** [Steccas/ProtonClient#8]
Hi, thanks for the app, it's really useful for me to use ProtonMail. But i have 2 feature requests that i think your desktop app should have which are below:

- Supporting multiple account logged in at the same time, for example i have 3 - 4 mail accounts and i would like to have notification for all of these emails if any new email is sent, user won't have to switch accounts from time to time.
- Desktop app password-protected, i thinnk this is kinda important for users because we all like ProtonMail for its privacy, what if people have physical access to our emails, right?

Please consider these requests. Thanks so much.

**Comment by Steccas** [comment]
Hi... I don't think that these features are feasible or useful, but I will leave this is issue open for some days in case anyone differs or wants to implement them.

- Since the client wraps around the web features of Proton Mail this is not very doable and would require a full fledged email client and this is not the case. Proton Mail offers an account switch in the upper corner, but to be fair to have multiple aliases you should switch to ProtonMail Plus; which is supported by the client.
- In my opinion, this is useless, to physically protect your mails, as stated in the readme, you should encrypt your disk and keep your user locked when away. A simple app password won't stop any attacker. In any case, you can logout from your account from the client.

Best regards.

**Comment by macbugs** [comment]
The requested features are supported by this application ...
https://github.com/vladimiry/ElectronMail
